<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /home/noir/Desktop/Projects/personal-webpage-front/static/models/typing-person.glb --root /models/ --printwidth 120 --precision 2
-->

<script>
	import { Group, LoopOnce } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf, useGltfAnimations, useSuspense } from '@threlte/extras';

	export const ref = new Group();
	export let animationQueue = [];
	const suspend = useSuspense();
	const gltf = suspend(useGltf('/models/typing-person.glb'));
	export let { actions, mixer } = useGltfAnimations(gltf, ref);
	export let allowGreet = () => {};

	const animateAction = (action = $actions['typing']) => {
		if (action) {
			action.clampWhenFinished = true;
			action.reset();
			action.play();
			action.loop = LoopOnce;
		}
	};

	$: animateAction($actions['Action']);

	mixer.addEventListener('finished', () => {
		for (const key in $actions) {
			if (Object.hasOwnProperty.call($actions, key)) $actions[key].stop();
		}
		if (animationQueue.length === 0) animateAction();
		else {
			const animation = animationQueue.shift();
			animateAction($actions[animation]);
			setTimeout(allowGreet, 1000);
		}
	});

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group name="Scene">
			<T.Group name="Armature" rotation={[-Math.PI, 0, 0]} scale={-1}>
				<T is={gltf.nodes.mixamorigHips} />
				<T.SkinnedMesh
					name="glasses"
					geometry={gltf.nodes.glasses.geometry}
					material={gltf.materials.rama}
					skeleton={gltf.nodes.glasses.skeleton}
				/>
				<T.SkinnedMesh
					name="hair"
					geometry={gltf.nodes.hair.geometry}
					material={gltf.materials.hair}
					skeleton={gltf.nodes.hair.skeleton}
				/>
				<T.Group name="person">
					<T.SkinnedMesh
						name="mixamomesh004"
						geometry={gltf.nodes.mixamomesh004.geometry}
						material={gltf.materials.skin}
						skeleton={gltf.nodes.mixamomesh004.skeleton}
					/>
					<T.SkinnedMesh
						name="mixamomesh004_1"
						geometry={gltf.nodes.mixamomesh004_1.geometry}
						material={gltf.materials['t-shirt']}
						skeleton={gltf.nodes.mixamomesh004_1.skeleton}
					/>
					<T.SkinnedMesh
						name="mixamomesh004_2"
						geometry={gltf.nodes.mixamomesh004_2.geometry}
						material={gltf.materials.trousers}
						skeleton={gltf.nodes.mixamomesh004_2.skeleton}
					/>
					<T.SkinnedMesh
						name="mixamomesh004_3"
						geometry={gltf.nodes.mixamomesh004_3.geometry}
						material={gltf.materials.eyes}
						skeleton={gltf.nodes.mixamomesh004_3.skeleton}
					/>
					<T.SkinnedMesh
						name="mixamomesh004_4"
						geometry={gltf.nodes.mixamomesh004_4.geometry}
						material={gltf.materials.hair}
						skeleton={gltf.nodes.mixamomesh004_4.skeleton}
					/>
				</T.Group>
				<T.Group name="shoes">
					<T.SkinnedMesh
						name="mixamomesh006"
						geometry={gltf.nodes.mixamomesh006.geometry}
						material={gltf.materials.shoes}
						skeleton={gltf.nodes.mixamomesh006.skeleton}
					/>
					<T.SkinnedMesh
						name="mixamomesh006_1"
						geometry={gltf.nodes.mixamomesh006_1.geometry}
						material={gltf.materials.shoes_1}
						skeleton={gltf.nodes.mixamomesh006_1.skeleton}
					/>
					<T.SkinnedMesh
						name="mixamomesh006_2"
						geometry={gltf.nodes.mixamomesh006_2.geometry}
						material={gltf.materials.skin}
						skeleton={gltf.nodes.mixamomesh006_2.skeleton}
					/>
				</T.Group>
			</T.Group>

			<T.Group name="laptop">
				<T.Mesh
					name="Cube002"
					geometry={gltf.nodes.Cube002.geometry}
					material={gltf.materials.keyboards}
				/>
				<T.Mesh
					name="Cube002_1"
					geometry={gltf.nodes.Cube002_1.geometry}
					material={gltf.materials.laptopdetails}
				/>
				<T.Mesh
					name="Cube002_2"
					geometry={gltf.nodes.Cube002_2.geometry}
					material={gltf.materials.display}
				/>
				<T.Mesh
					name="Cube002_3"
					geometry={gltf.nodes.Cube002_3.geometry}
					material={gltf.materials.laptop_01}
				/>
			</T.Group>
			<T.Group name="chair">
				<T.Mesh
					name="Cube027"
					geometry={gltf.nodes.Cube027.geometry}
					material={gltf.materials.chair}
				/>
				<T.Mesh
					name="Cube027_1"
					geometry={gltf.nodes.Cube027_1.geometry}
					material={gltf.materials.chairpillow}
				/>
			</T.Group>
			<T.Group name="table">
				<T.Mesh
					name="Cube003"
					geometry={gltf.nodes.Cube003.geometry}
					material={gltf.materials.table_wood_01}
				/>
				<T.Mesh
					name="Cube003_1"
					geometry={gltf.nodes.Cube003_1.geometry}
					material={gltf.materials.table_legs_01}
				/>
			</T.Group>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
