/*
 * Builds the geography behind the dot-matrix Earth of the background scene.
 *
 *   node scripts/scene-geodata.js
 *
 * Input:  src/lib/ne_110m_admin_0_countries.geojson (Natural Earth 1:110m, public domain)
 * Output: src/lib/entities/globe/landMask.js      — 0.5° land raster, run-length encoded
 *         src/lib/entities/globe/countryBorders.js — every country's rings, delta encoded
 *
 * The old globe shipped ~1.2 MB of JSON points. The raster is a few kB and lets each
 * quality tier choose its own dot spacing. The borders let the globe emphasise whichever
 * country `src/lib/config/site-config.json` names as home, without regenerating anything
 * when that config changes. Check the code lookup with `node scripts/check-country-codes.js`.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

// written through the repo's prettier config, so `pnpm lint` stays quiet about them
const prettier = createRequire(import.meta.url)('prettier');
const writeModule = (file, source) =>
	writeFileSync(
		file,
		prettier.format(source, { ...prettier.resolveConfig.sync(file), filepath: file })
	);

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SOURCE = resolve(root, 'src/lib/ne_110m_admin_0_countries.geojson');
const MASK_TARGET = resolve(root, 'src/lib/entities/globe/landMask.js');
const BORDERS_TARGET = resolve(root, 'src/lib/entities/globe/countryBorders.js');

/* base64url alphabet; the decoder in src/lib/entities/globe/geodata.js mirrors it */
const DIGITS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_';

const geojson = JSON.parse(readFileSync(SOURCE, 'utf8'));

const polygonsOf = ({ geometry }) =>
	geometry.type === 'Polygon' ? [geometry.coordinates] : geometry.coordinates;

/* ------------------------------------------------------------------ land raster -- */

const STEP = 0.5; // degrees per cell
const WIDTH = 360 / STEP;
const HEIGHT = 180 / STEP;
const mask = new Uint8Array(WIDTH * HEIGHT);

for (const feature of geojson.features) {
	for (const rings of polygonsOf(feature)) {
		let minLat = Infinity;
		let maxLat = -Infinity;
		for (const ring of rings) {
			for (const [, lat] of ring) {
				minLat = Math.min(minLat, lat);
				maxLat = Math.max(maxLat, lat);
			}
		}

		// Scanline even-odd fill of one polygon (outer ring and holes together).
		for (let row = 0; row < HEIGHT; row++) {
			const lat = 90 - (row + 0.5) * STEP;
			if (lat < minLat || lat > maxLat) continue;

			const crossings = [];
			for (const ring of rings) {
				for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
					const [lon1, lat1] = ring[j];
					const [lon2, lat2] = ring[i];
					if (lat1 > lat === lat2 > lat) continue;
					crossings.push(lon1 + ((lat - lat1) * (lon2 - lon1)) / (lat2 - lat1));
				}
			}
			crossings.sort((a, b) => a - b);

			for (let k = 0; k + 1 < crossings.length; k += 2) {
				const from = Math.ceil((crossings[k] + 180) / STEP - 0.5);
				const to = Math.floor((crossings[k + 1] + 180) / STEP - 0.5);
				for (let col = Math.max(0, from); col <= Math.min(WIDTH - 1, to); col++) {
					mask[row * WIDTH + col] = 1;
				}
			}
		}
	}
}

/* Runs alternate water/land starting with water, two digits each (runs ≤ 720 < 64²). */
let rle = '';
let landCells = 0;
for (let row = 0; row < HEIGHT; row++) {
	let value = 0;
	let run = 0;
	for (let col = 0; col < WIDTH; col++) {
		const cell = mask[row * WIDTH + col];
		landCells += cell;
		if (cell === value) {
			run++;
		} else {
			rle += DIGITS[run >> 6] + DIGITS[run & 63];
			value = cell;
			run = 1;
		}
	}
	rle += DIGITS[run >> 6] + DIGITS[run & 63];
}

writeModule(
	MASK_TARGET,
	`/*
 * GENERATED by scripts/scene-geodata.js from Natural Earth 1:110m countries — do not edit.
 *
 * ${WIDTH}×${HEIGHT} land raster (${STEP}° cells, row 0 = 90°N, column 0 = 180°W), run-length
 * encoded per row: runs alternate water/land starting with water, two base-64 digits each.
 */
export const LAND_MASK_WIDTH = ${WIDTH};
export const LAND_MASK_HEIGHT = ${HEIGHT};
export const LAND_MASK_STEP = ${STEP};
export const LAND_MASK_RLE =
	'${rle}';
`
);

/* -------------------------------------------------------------- country borders -- */

/*
 * Each ring: vertices quantised to 1/QUANT degree, first one absolute, the rest as
 * deltas; every number zigzag-encoded as a varint of 5-bit groups (bit 5 = "more").
 * Rings are joined with "~". The closing vertex that repeats the first one is dropped.
 */
const QUANT = 20; // 0.05° — well under the 1:110m vertex spacing

const varint = (value) => {
	let v = value < 0 ? -value * 2 - 1 : value * 2;
	let out = '';
	while (v >= 32) {
		out += DIGITS[32 | (v & 31)];
		v = Math.floor(v / 32);
	}
	return out + DIGITS[v];
};

const encodeRing = (ring) => {
	const points = ring.slice(0, -1);
	let prevLon = 0;
	let prevLat = 0;
	let out = '';
	for (const [lon, lat] of points) {
		const qLon = Math.round(lon * QUANT);
		const qLat = Math.round(lat * QUANT);
		out += varint(qLon - prevLon) + varint(qLat - prevLat);
		prevLon = qLon;
		prevLat = qLat;
	}
	return out;
};

const code = (value) => (typeof value === 'string' && /^[A-Z]{3}$/.test(value) ? value : null);

const countries = geojson.features.map((feature) => {
	const { properties } = feature;
	const rings = polygonsOf(feature).flat();
	let [west, south, east, north] = [Infinity, Infinity, -Infinity, -Infinity];
	for (const ring of rings) {
		for (const [lon, lat] of ring) {
			west = Math.min(west, lon);
			east = Math.max(east, lon);
			south = Math.min(south, lat);
			north = Math.max(north, lat);
		}
	}
	return {
		iso: code(properties.ISO_A3),
		adm: code(properties.ADM0_A3),
		name: properties.NAME,
		bbox: [west, south, east, north].map((v) => Math.round(v * 100) / 100),
		rings: rings.map(encodeRing).join('~')
	};
});

writeModule(
	BORDERS_TARGET,
	`/*
 * GENERATED by scripts/scene-geodata.js from Natural Earth 1:110m countries — do not edit.
 *
 * One entry per Natural Earth feature: ISO 3166-1 alpha-3 code (null where Natural Earth
 * has "-99"), ADM0_A3 code (always set), English name, bbox [west, south, east, north] and
 * all polygon rings. Ring encoding: see decodeRings() in ./geodata.js (1/${QUANT}° units).
 */
export const BORDER_QUANT = ${QUANT};

export const COUNTRIES = [
${countries.map((c) => '\t' + JSON.stringify(c)).join(',\n')}
];
`
);

console.log(
	`land mask ${WIDTH}x${HEIGHT}: ${((100 * landCells) / mask.length).toFixed(1)}% land, ${
		rle.length
	} chars\n` +
		`borders: ${countries.length} countries, ${countries.reduce(
			(n, c) => n + c.rings.length,
			0
		)} chars`
);
